# -*- coding: UTF-8 -*-
#
# generated by wxGlade not found on Thu Oct 29 00:57:44 2015 from "/home/devin/Documents/ShuffleIR-Mobile/ShuffleFrame.wxg"
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class dialogListWindows(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: dialogListWindows.__init__
        wx.Dialog.__init__(self, *args, **kwds)
        self.list_box_3 = wx.ListBox(self, wx.ID_ANY, choices=[], style=wx.LB_ALWAYS_SB | wx.LB_SINGLE)
        self.button_12 = wx.Button(self, wx.ID_ANY, _("Select"))
        self.button_13 = wx.Button(self, wx.ID_ANY, _("Cancel"))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: dialogListWindows.__set_properties
        self.SetTitle(_("dialog_1"))
        self.list_box_3.SetMinSize(wx.DLG_SZE(self.list_box_3, (300, 100)))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: dialogListWindows.__do_layout
        sizer_9 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_2 = wx.GridSizer(1, 2, 1, 1)
        sizer_9.Add(self.list_box_3, 0, wx.ALIGN_CENTER | wx.EXPAND, 0)
        grid_sizer_2.Add(self.button_12, 0, wx.ALIGN_RIGHT, 0)
        grid_sizer_2.Add(self.button_13, 0, 0, 0)
        sizer_9.Add(grid_sizer_2, 1, wx.ALIGN_CENTER | wx.EXPAND, 0)
        self.SetSizer(sizer_9)
        sizer_9.Fit(self)
        self.Layout()
        # end wxGlade

# end of class dialogListWindows
