# -*- coding: UTF-8 -*-
#
# generated by wxGlade not found on Thu Oct 29 14:54:17 2015 from "/home/devin/Documents/ShuffleIR-Mobile/ShuffleFrame.wxg"
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


import dataNationalDex


class dialogNewIcon(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: dialogNewIcon.__init__
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_3 = wx.StaticText(self, wx.ID_ANY, _("What is this icon?"), style=wx.ALIGN_LEFT)
        self.list_box_1 = wx.ListBox(self, wx.ID_ANY, choices=[], style=wx.LB_NEEDED_SB | wx.LB_SINGLE)
        self.checkbox_1 = wx.CheckBox(self, wx.ID_ANY, _("With Barrier or not?"))
        self.button_11 = wx.Button(self, wx.ID_ANY, _("Save"))
        self.button_14 = wx.Button(self, wx.ID_ANY, _("Cancel"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.onSave, self.button_11)
        self.Bind(wx.EVT_BUTTON, self.onCancel, self.button_14)
        # end wxGlade

        self.list_box_1.Clear()
        for key in dataNationalDex.keys:
            self.list_box_1.Append(key + " : " + dataNationalDex.list.get(key))
        
        self.list_box_1.SetSelection(0)
        self.nameIcon = ''
        self.keyIcon = ''
        
    def __set_properties(self):
        # begin wxGlade: dialogNewIcon.__set_properties
        self.SetTitle(_("dialog_2"))
        self.list_box_1.SetMinSize((240, 240))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: dialogNewIcon.__do_layout
        sizer_10 = wx.BoxSizer(wx.VERTICAL)
        sizer_10.Add(self.label_3, 0, wx.ALIGN_CENTER | wx.EXPAND, 0)
        sizer_10.Add(self.list_box_1, 0, 0, 0)
        sizer_10.Add(self.checkbox_1, 0, wx.ALIGN_CENTER | wx.EXPAND, 0)
        sizer_10.Add(self.button_11, 0, wx.ALIGN_CENTER | wx.EXPAND, 0)
        sizer_10.Add(self.button_14, 0, wx.ALIGN_CENTER | wx.EXPAND, 0)
        self.SetSizer(sizer_10)
        sizer_10.Fit(self)
        self.Layout()
        # end wxGlade

    def onSave(self, event):  # wxGlade: dialogSelectIcons.<event_handler>
        #
        index = self.list_box_1.GetSelection()
        self.keyIcon = dataNationalDex.keys[index]
        if self.checkbox_1.IsChecked():
            self.nameIcon = self.keyIcon + '-i'
        else:                
            self.nameIcon = self.keyIcon 
        
        self.EndModal(wx.OK)

    def onCancel(self, event):  # wxGlade: dialogSelectIcons.<event_handler>
        self.EndModal(wx.CANCEL)
        
# end of class dialogNewIcon
